services:
  - type: web
    name: cool-cucumbers-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn backend.app:app"
    plan: free
    autoDeploy: true
